#!/bin/tcsh -f

if($# != 1) then
        echo "argument 1 = wordlist"
        exit(-1)
endif
 
set i = 1
set tot = `cat $1 | wc -l`
while ($i <= $tot)

	set a = `cat $1 | head -$i | tail -1`
	echo $a $a  >> lexicon/dict

@ i++
end
