#!/bin/tcsh -f
if ($# != 1) then
	echo "arg1 - phn"
	exit(-1)
endif

set i = 1

set tot = `cat $1 | wc -l`
echo "SIL" > data/temp.lab
while ($i <= $tot)
  set a = `cat $1 | head -$i | tail -1`
  echo $a >> data/temp.lab
  @ i++
end

echo "SIL" >> data/temp.lab ###for parser###

