#!/bin/tcsh -f

if ($# != 2) then
	echo "Arg1 --> word.lab"
	echo "Arg2 --> Input_text_file"
	exit(-1)
endif


set num_words = `cat $2 |wc -w`

set word_start = 1
while ($word_start <= $num_words)
	set word = `cat $2 | cut -d " " -f$word_start`
	echo ME $word >>data/word
	@ word_start++
end


set num_ch = `cat $1 |wc -w`
set st = 1

while ($st <= $num_ch)
	set ch1 = `cat $1 |head -$st |tail -1`
	#echo $ch1
		@ st1 = $st + 1
            set ch2 = `cat $1 |head -$st1 |tail -1`
		#echo $ch2
		@ st2 = $st + 2
            set ch3 = `cat $1 |head -$st2 |tail -1`
		#echo $ch3
		@ st3 = $st + 3
            set ch4 = `cat $1 |head -$st3 |tail -1`
		#echo $ch4
		@ st4 = $st + 4
            set ch5 = `cat $1 |head -$st4 |tail -1`
		#echo $ch4
		@ st5 = $st + 5
            set ch6 = `cat $1 |head -$st5 |tail -1`
		#echo $ch6
		@ st6 = $st + 6
            set ch7 = `cat $1 |head -$st6 |tail -1`
		#echo $ch7
		@ st7 = $st + 7
	    set ch8 = `cat $1 |head -$st7 |tail -1`
	    	@ st8 = $st + 8
	    set ch9 = `cat $1 |head -$st8 |tail -1`
	    	@ st9 = $st + 9
	    set ch10 = `cat $1 |head -$st9 |tail -1`
	    	@ st10 = $st + 10
	    set ch11 = `cat $1 |head -$st10 |tail -1`
	    	@ st11 = $st + 11
	    set ch12 = `cat $1 |head -$st11 |tail -1`
	if (($ch12 == SIL && $ch11 != SIL && $ch10 != SIL && $ch9 != SIL && $ch8 != SIL && $ch7 != SIL && $ch6 != SIL && $ch5 != SIL && $ch4 != SIL && $ch3 != SIL && $ch2 != SIL && $ch1 != SIL) && ($st <= $num_ch - 11)) then
		echo $ch1 $ch2 $ch3 $ch4 $ch5 $ch6 $ch7 $ch8 $ch9 $ch10 $ch11 >>data/word1
		@ st = $st + 11
	else if (($ch11 == SIL && $ch10 != SIL && $ch9 != SIL && $ch8 != SIL && $ch7 != SIL && $ch6 != SIL && $ch5 != SIL && $ch4 != SIL && $ch3 != SIL && $ch2 != SIL && $ch1 != SIL) && ($st <= $num_ch - 10)) then
		echo $ch1 $ch2 $ch3 $ch4 $ch5 $ch6 $ch7 $ch8 $ch9 $ch10 >>data/word1
		@ st = $st + 10
 	else if (($ch10 == SIL && $ch9 != SIL && $ch8 != SIL && $ch7 != SIL && $ch6 != SIL && $ch5 != SIL && $ch4 != SIL && $ch3 != SIL && $ch2 != SIL && $ch1 != SIL) && ($st <= $num_ch - 9)) then
		echo $ch1 $ch2 $ch3 $ch4 $ch5 $ch6 $ch7 $ch8 $ch9 >>data/word1
		@ st = $st + 9
	else if (($ch9 == SIL && $ch8 != SIL && $ch7 != SIL && $ch6 != SIL && $ch5 != SIL && $ch4 != SIL && $ch3 != SIL && $ch2 != SIL && $ch1 != SIL) && ($st <= $num_ch - 8)) then
		echo $ch1 $ch2 $ch3 $ch4 $ch5 $ch6 $ch7 $ch8 >>data/word1
		@ st = $st + 8
	else if (($ch8 == SIL && $ch7 != SIL && $ch6 != SIL && $ch5 != SIL && $ch4 != SIL && $ch3 != SIL && $ch2 != SIL && $ch1 != SIL) && ($st <= $num_ch - 7)) then
		echo $ch1 $ch2 $ch3 $ch4 $ch5 $ch6 $ch7 >>data/word1
		@ st = $st + 7
	else if (($ch7 == SIL && $ch6 != SIL && $ch5 != SIL && $ch4 != SIL && $ch3 != SIL && $ch2 != SIL && $ch1 != SIL) && ($st <= $num_ch - 6)) then
		echo $ch1 $ch2 $ch3 $ch4 $ch5 $ch6 >>data/word1
		@ st = $st + 6
	else if (($ch6 == SIL && $ch5 != SIL && $ch4 != SIL && $ch3 != SIL && $ch2 != SIL && $ch1 != SIL) && ($st <= $num_ch - 5)) then
		echo $ch1 $ch2 $ch3 $ch4 $ch5 >>data/word1
		@ st = $st + 5
	else if (($ch5 == SIL && $ch4 != SIL && $ch3 != SIL && $ch2 != SIL && $ch1 != SIL) && ($st <= $num_ch - 4)) then
		echo $ch1 $ch2 $ch3 $ch4 >>data/word1
		@ st = $st + 4
	else if (($ch4 == SIL && $ch3 != SIL && $ch2 != SIL && $ch1 != SIL) && ($st <= $num_ch - 3)) then
		echo $ch1 $ch2 $ch3 >>data/word1
		@ st = $st + 3
	else if (($ch3 == SIL && $ch2 != SIL && $ch1 != SIL) && ($st <= $num_ch - 2)) then
		echo $ch1 $ch2 >>data/word1
		@ st = $st + 2
	else if (($ch2 == SIL && $ch1 != SIL) && ($st <= $num_ch - 1)) then
		echo $ch1 >>data/word1
	#else
		#echo $ch1 >>data/word1
	endif
	@ st++
end
paste data/word data/word1 >>data/word2
cp -R data/temp.rec data/temp_word.lab
HLEd data/word2 data/temp_word.lab

